## =================================================================
## storage.tf
## Dedicated resource group + ADLS Gen2 storage account for this
## project, with two containers: raw (untouched dirty JSON) and
## clean (Databricks output, auto-ingested by Snowpipe).
## =================================================================

resource "azurerm_resource_group" "fintech" {
  name     = var.resource_group_name
  location = var.location
}

resource "azurerm_storage_account" "fintech" {
  name                     = "stfintechpipeline01"
  resource_group_name      = azurerm_resource_group.fintech.name
  location                 = azurerm_resource_group.fintech.location
  account_tier             = "Standard"
  account_replication_type = "LRS"

  # is_hns_enabled turns a regular Blob Storage account into ADLS
  # Gen2 (hierarchical namespace) -- required for Databricks/Data
  # Factory to treat paths as a real filesystem, not flat blob keys.
  is_hns_enabled = true
}

# Raw landing zone: untouched dirty JSON as generated by the script,
# uploaded here by Data Factory. Never modified after landing --
# kept as an audit trail / replay source.
resource "azurerm_storage_container" "raw" {
  name                  = "raw"
  storage_account_name  = azurerm_storage_account.fintech.name
  container_access_type = "private"
}

resource "azurerm_storage_container" "clean" {
  name                  = "clean"
  storage_account_name  = azurerm_storage_account.fintech.name
  container_access_type = "private"
}